name: Build

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP image
        uses: docker/build-push-action@v6
        with:
          target: php
          push: true
          tags: |
            ghcr.io/sporkcode/wordpress-php:${{ github.event.release.tag_name }}
            ghcr.io/sporkcode/wordpress-php:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build Nginx image
        uses: docker/build-push-action@v6
        with:
          target: nginx
          push: true
          tags: |
            ghcr.io/sporkcode/wordpress-nginx:${{ github.event.release.tag_name }}
            ghcr.io/sporkcode/wordpress-nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
