name: Wordpress Image Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and publish images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (php)
        uses: docker/build-push-action@v4
        with:
          context: .
          target: php
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sporkcode/wordpress-php:latest
            ghcr.io/sporkcode/wordpress-php:6.1.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push (nginx)
        uses: docker/build-push-action@v4
        with:
          context: .
          target: nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sporkcode/wordpress-nginx:latest
            ghcr.io/sporkcode/wordpress-nginx:6.1.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
