name: Test Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP image
        uses: docker/build-push-action@v6
        with:
          target: php
          push: false
          tags: ghcr.io/sporkcode/wordpress-php:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Nginx image
        uses: docker/build-push-action@v6
        with:
          target: nginx
          push: false
          tags: ghcr.io/sporkcode/wordpress-nginx:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
